### ISSUE TITLE
/login

### ISSUE THREAD

**Issue by zzc-tongji** [TeamYouthChina/frontend#226]
Login 页面

左右需要完全对称（50 vw）。

左侧图片居中，大小用vw（`max-width: 20vw`）。

右边两个 slogan 改为 https://weyouth-frontend.oss-us-east-1.aliyuncs.com/234743988c2c0576fe7129e989f68cac.png

底部 facebook, google 等等删掉。

**Comment by gnotuyg** [comment]
complete
