### ISSUE TITLE
/register

### ISSUE THREAD

**Issue by zzc-tongji** [TeamYouthChina/frontend#229]
Register 页面

左右需要完全对称（50 vw）。

左侧图片居中，大小用vw（max-width: 20vw）。

右边两个 slogan 改为 https://weyouth-frontend.oss-us-east-1.aliyuncs.com/234743988c2c0576fe7129e989f68cac.png

完善个人信息的subpage去掉，直接注册按钮

需要用户输入的部分，参考 https://github.com/TeamYouthChina/backend/issues/495

密码输入的地方，要求用户输入两次，判定两次必须相同

日期选择可以使用 MDB 的 Datepicker。

**Comment by gnotuyg** [comment]
Datepicker 和整体风格不搭，目前注册页面用户只需要用户填写姓名，邮箱以及密码。生日和性别均为默认，倾向于在个人信息界面更改。

**Comment by YihaoGuo2018** [comment]
按照你的想法改，把功能实现出来
