### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zzc-tongji** [TeamYouthChina/frontend#237]
```
/article/1
```

1. 评论右边三个点加删除评论（仅删除自己）
2. 分享删掉（代码注释掉）
3. 文章放到 cell 里面 右侧 padding 删掉
4. 底部上一页下一页加上灰色框
5. 收藏文章，收藏博主（暂时没上）放右边
6. 收起评论删掉
7. 评论的回复，点完发布后收起
8. 只写一级评论，所有二级部分隐藏
9. 发布评论 IMG 去掉
10. 评论 IMG 右边带一个名字
11. 收藏按钮改成点赞的灰色字
12. 头像右边加名字
13. 编辑文章按钮

```
/article/1/edit
```

1. 权限：get article 后，判断用户 id 不对，跳回查看页
2. 相似的地方还有：问题、答案、短则

```
/question/1
/question/1/answer/1
```

1. 一条回答、更多回答：删除
2. 仿照文章
3. 相关回答：删掉
4. 关注问题：删掉
5. 分享删掉（代码注释掉）

```
/question/1/answer/1/edit
/question/1/answer/create
```

1. bug 总是跳到 404 页面

**Comment by FTDRefrain** [comment]
`/article/1`
1. 5里面的收藏博主右边是哪里？和UI一样是吗？
1. 13的话默认不是当前文章作者不显示编辑按钮
1. 同样评论的三个点也是默认不是自己的不显示三个点

`/question/1`
1. 4的关注问题只最右边的收藏？

`/question/1/answer/1/edit`
`/question/1/answer/create`
1. 跳转是因为用户已经回答了问题1，且答案id不是1，所以无权编辑该回答和创建新回答
1. 先偷懒都改成跳回`/question/1`且回答只能通过按钮过去

**Comment by YihaoGuo2018** [comment]
/article/1

5收藏博主先不放
13是
默认不是自己的不显示三个点
/question/1

4先只有收藏问题
/question/1/answer/1/edit
/question/1/answer/create

跳转是因为用户已经回答了问题1，且答案id不是1，所以无权编辑该回答和创建新回答
先偷懒都改成跳回/question/1且回答只能通过按钮过去

**Comment by FTDRefrain** [comment]
待测试
