### ISSUE TITLE
answer-card

### ISSUE THREAD

**Issue by zzc-tongji** [TeamYouthChina/frontend#41]
两个 AnswerCard，`index.data.js` 内置，目录下面只保留 `index.js` 一个文件，其余放文件夹。

**Comment by zzc-tongji** [comment]
细节改动：

- 所以单位全部改为 vw。
- 视觉效果需要和 Figma 一致。
- MDB 中的响应式布局标签 `xl lg md sm` 全部去掉
  - MDB React：改 `xl lg md sm` 为 `size`
  - MDB jQuert：删去 class 中的 `xl lg md sm`，例如：改 `col-md-5` 为 `col-5`

---

做完以后，将 Teambition 中的任务移动到“已完成 UI”，然后把这个 issue 关上。

**Comment by FTDRefrain** [comment]
pr to master
