### ISSUE TITLE
article-card

### ISSUE THREAD

**Issue by zzc-tongji** [TeamYouthChina/frontend#43]
先把 answer-card 改好，然后按照 answer-card 的模式写一下 article-card-bar-unauth。最后按照 article-card-bar-unauth 改 article-card-bar-auth。

注意，article-card-bar-unauth 只准动 render return 内的部分！

**Comment by zzc-tongji** [comment]
细节改动：

- 所以单位全部改为 vw。
- 视觉效果需要和 Figma 一致。
- MDB 中的响应式布局标签 `xl lg md sm` 全部去掉
  - MDB React：改 `xl lg md sm` 为 `size`
  - MDB jQuert：删去 class 中的 `xl lg md sm`，例如：改 `col-md-5` 为 `col-5`

---

做完以后，将 Teambition 中的任务移动到“已完成 UI”，然后把这个 issue 关上。

**Comment by FTDRefrain** [comment]
pr to master
