### ISSUE TITLE
API修改

### ISSUE THREAD

**Issue by ziyuanwei96** [TeamYouthChina/frontend#75]
除了discover剩下的标签都添加了一个parameter属性: X-AUTHENTICATION
添加了5个标签类:
'/applicants/{id}/educations/{educationID}'
'/applicants/{id}/projects/{projectID}'
'/applicants/{id}/experiences/{experienceID}'
'/applicants/{id}/certificates/{certificateID}'
'/applicants/{id}/extracurriculars/{extracurricularID}'

**Comment by zzc-tongji** [comment]
泽培看一下。
